module.exports= {
    fullname: 'Воид Ада',
    birthday: '1994',
    location: 'г. Калининград, Россия',
    skype: 'oxiggy',
    email: 'oxiggy@oxiggy.com',
    date: '30.06.2019',
    about: 'Мне понравилось ваше обманчиво простое тестовое задание, от работы ожидаю похожих интересных испытаний.',
    level: 42,
    skills: [
        { label: 'БЭМ/OOCSS', checked: true },
        { label: 'Pug (Jade)', checked: true },
        { label: 'Stylus/LESS/SASS', checked: true },
        { label: 'Работаю с SVG', checked: false },
        { label: 'Верстаю семантично', checked: true },
        { label: 'Accessibility (A11Y)', checked: true },
        { label: 'ES2015/ES2016', checked: true },
        { label: 'Gulp/GRUNT', checked: false },
        { label: 'Webpack', checked: true },
        { label: 'Дружу с WebGL', checked: false },
        { label: 'jQuery', checked: true },
        { label: 'Знаю/изучаю Angular', checked: false },
        { label: 'Знаю/изучаю React', checked: true },
        { label: 'Знаю/изучаю Node.js', checked: true },
        { label: 'Использую Git', checked: true },
        { label: 'С глазомером <span style="position: relative; top: 1px;">всё</span> <span style="position: relative; top: 2px;">ок</span>', checked: true },
        { label: 'Читаю <a href="https://blog.csssr.ru/">blog.csssr.ru</a>', checked: false },
        { label: 'Я ленивый(-ая)', checked: false },
        { label: 'У меня хороший английский', checked: false },
    ],
    plans: [
        { label: 'Верстать', checked: true },
        { label: 'Прокачиваться в JS', checked: false },
        { label: 'Менеджерство', checked: false },
        { label: 'Другое', checked: false },
    ],
}
