module.exports= {
    fullname: 'Иванов Иван Иванович',
    birthday: '1990',
    location: 'г. Иваново, Россия',
    skype: 'ivanov',
    email: 'ivanov@gmail.com',
    date: '11.06.2019',
    about: 'Ну-ууу-уу... Ээээ...',
    skills: [
        { label: 'БЭМ/OOCSS', checked: true },
        { label: 'Pug (Jade)', checked: true },
        { label: 'Stylus/LESS/SASS', checked: true },
        { label: 'Работаю с SVG', checked: true },
        { label: 'Верстаю семантично', checked: true },
        { label: 'Accessibility (A11Y)', checked: true },
        { label: 'ES2015/ES2016', checked: true },
        { label: 'Gulp/GRUNT', checked: false },
        { label: 'Webpack', checked: true },
        { label: 'Дружу с WebGL', checked: false },
        { label: 'jQuery', checked: true },
        { label: 'Знаю/изучаю Angular', checked: false },
        { label: 'Знаю/изучаю React', checked: true },
        { label: 'Знаю/изучаю Node.js', checked: true },
        { label: 'Использую Git', checked: true },
        { label: 'С глазомером <span style="position: relative; top: 1px;">всё</span> <span style="position: relative; top: 2px;">ок</span>', checked: true },
        { label: 'Читаю <a >blog.csssr.ru</a>', checked: false },
        { label: 'Я ленивый(-ая)', checked: false },
        { label: 'У меня хороший английский', checked: false },
    ],
    plans: [
        { label: 'Верстать', checked: true },
        { label: 'Прокачиваться в JS', checked: false },
        { label: 'Менеджерство', checked: false },
        { label: 'Другое', checked: false },
    ],
}
